import '@/assets/styles/globals.scss'
import Navbar from '@/components/navbar'
import { TransitionProvider } from '@/context/transitionProvider'
import CursorProvider from '@/providers/cursorProvider'
import ReactLenis from 'lenis/react'
import { Anton, Exo_2, Fira_Code } from 'next/font/google'
import React from 'react'

const firaCode = Fira_Code({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-firacode',
})

const exo2 = Exo_2({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-exo2',
})

const anton = Anton({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-anton',
})

export const metadata = {
    title: 'Nahid Portfolio',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body
                className={`${firaCode.variable} ${exo2.variable} ${anton.variable}`}
            >
                <ReactLenis options={{ duration: 2 }} root>
                    <TransitionProvider>
                        <div className="overflow-x-hidden">
                            <CursorProvider />
                            <Navbar />
                            {children}
                        </div>
                    </TransitionProvider>
                </ReactLenis>
            </body>
        </html>
    )
}

export default RootLayout
